apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: benchmark
type: Opaque
stringData:
  username: postgres
  password: postgres
  url: r2dbc:postgresql://postgres-service:5432/benchmark
  jdbc-url: jdbc:postgresql://postgres-service:5432/benchmark
