spring.application.name=microservers

# Postgres configuration
spring.r2dbc.url=r2dbc:postgresql://db:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# Connection pool to postgres
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.initial-size=50

# Reactive sockets configuration
spring.rsocket.server.port=7000
spring.rsocket.server.transport=tcp