global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-mvc-http'
    static_configs:
      - targets: ['app-mvc:8080']
        labels:
          variant: 'mvc-http'

  - job_name: 'webflux-http'
    static_configs:
      - targets: ['app-webflux:8080']
        labels:
          variant: 'webflux-http'