spring.application.name=microservers

# Postgres configuration
spring.r2dbc.url=r2dbc:postgresql://db:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# gRPC ????
spring.grpc.server.port=9090

# Connection pool to postgres
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.initial-size=50