spring.application.name=microservers

# Postgres configuration
spring.r2dbc.url=r2dbc:postgresql://postgres-service:5432/benchmark
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# Connection pool to postgres
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.initial-size=50