version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    ports: ["8093:9090"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    networks: [test-net]

  grafana:
    image: grafana/grafana:latest
    ports: ["8094:3000"]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks: [test-net]
    depends_on: [prometheus]

  app-consumer:
    build: ./ConsumeService
    ports: ["8091:8080"]
    networks: [test-net]

  app-process:
    build: ./ProcessService
    ports: ["8092:8080"]
    networks: [test-net]

networks:
  test-net:
    driver: bridge