spring.application.name=microservers

spring.grpc.client.channels.process-service.address=${GRPC_PROCESS_SERVICE_ADDRESS:static://localhost:9090}
spring.grpc.client.channels.process-service.negotiation-type=plaintext